---

  nxos_provider:
    username: "{{ user }}"
    # 'user' is set in the hosts file, otherwise needs 
    # to be on CLI invocation
    #password: "{{ pwd }}" -- pjw: using PKI
    transport: network_cli
    host: "{{ inventory_hostname }}"

  features:
  - { feature: bgp }
  - { feature: ospf }
  - { feature: "nv overlay" }
  - { feature: pim }

  l3_interfaces:
  #- { interface: Ethernet1/1 } 
  # pjw: this is my mgmt connection, not needed
  # for config-building demo purposes
  - { interface: Ethernet1/2 }
  - { interface: Ethernet1/3 }
  - { interface: Ethernet1/4 }
  - { interface: Ethernet1/5 }
  - { interface: Ethernet1/6 }
  - { interface: Ethernet1/7 }
  - { interface: Ethernet1/8 }

  ospf_process_id: Underlay

  ospf_area: 0
  
  asn: 65001

  address_families:
  - { afi: l2vpn, safi: evpn }
  
  bgp_neighbors:
  - { remote_as: 65001, neighbor: 10.2.2.1, update_source: Loopback0 }
  - { remote_as: 65001, neighbor: 10.2.2.2, update_source: Loopback0 }
  - { remote_as: 65001, neighbor: 10.2.2.3, update_source: Loopback0 }
  - { remote_as: 65001, neighbor: 10.2.2.4, update_source: Loopback0 }

  s1_loopback: 10.2.1.1

  s2_loopback: 10.2.1.2

  rp_address: 100.2.1.1