
    - name: ENABLE FEATURES
      nxos_feature:
        feature: "{{item.feature }}"
        provider: "{{ nxos_provider }}"
      with_items: "{{ features }}"

    - name: CONFIGURE PHYSICAL L3 INTERFACES
      nxos_interface:
        interface: "{{item.interface }}"
        mode: layer3
        admin_state: up
        provider: "{{ nxos_provider }}"
      with_items: "{{ l3_interfaces }}"

    - name: CONFIGURE LOOPBACK INTERFACES
      nxos_interface:
        interface: "{{ item.interface }}"
        provider: "{{ nxos_provider }}"
      with_items: "{{ loopbacks }}"

    - name: ENABLE NV OVERLAY EVPN
      nxos_evpn_global:
        nv_overlay_evpn: true
        provider: "{{ nxos_provider }}"

    - name: CONFIGURE BGP ASN AND ROUTER ID
      nxos_bgp:
        asn: "{{ asn }}"
        router_id: "{{ router_id }}"
        provider: "{{ nxos_provider }}"
        state: present

    - name: CONFIGURE BGP NEIGHBORS
      nxos_bgp_neighbor:
        asn: "{{ asn }}"
        neighbor: "{{ item.neighbor }}"
        remote_as: "{{ item.remote_as }}"
        update_source: "{{ item.update_source }}"
        provider: "{{ nxos_provider }}"
      with_items: "{{ bgp_neighbors }}"

    - name: CONFIGURE L2VPN EVPN ADDRESS FAMILY FOR BGP NEIGHBORS
      nxos_bgp_neighbor_af:
        asn: "{{ asn }}"
        neighbor: "{{ item.neighbor }}"
        afi: l2vpn
        safi: evpn
        send_community: both
        route_reflector_client: "false"
        provider: "{{ nxos_provider }}"
      with_items: "{{ bgp_neighbors }}"

    - name: CONFIGURE TENANT VRFs
      nxos_vrf:
        vrf: "{{ item.vrf }}"
        vni: "{{ item.vni_id }}"
        rd: auto
        state: present
        provider: "{{ nxos_provider }}"
      with_items: "{{ vrfs2 }}"

    - name: CONFIGURE TENANT VRFs (cont'd)
      nxos_vrf_af:
        vrf: "{{ item.vrf }}"
        afi: ipv4
        #safi: unicast
        route_target_both_auto_evpn: yes
        state: present
        #m_facts: true
        provider: "{{ nxos_provider }}"
      with_items: "{{ vrfs2 }}"
